### ISSUE TITLE
Can't get an expected UI

### ISSUE THREAD

**Issue by alex-konoval** [shydie/scheduling-app#1]
Hey, @shydie 
I tried to run your project and this what I get. Is this an expected result or I did something wrong?
I used `yarn start`.

https://user-images.githubusercontent.com/8490547/116064287-890f9a00-a68e-11eb-9485-cc10e3547c7d.mov

**Comment by shydie** [comment]
Hey @alex-konoval 
Since there's no index route yet
https://github.com/shydie/scheduling-app/blob/4611e04073d7513c4986e7deb5f59ceb75034d40/app/router.ts#L9-L15
(it should be clinician, but it's empty for now) you can try to go to the /services page and there will be presented needed functionality.
Sorry for the confusion, I'll add a redirect from the index to services to fix that.

**Comment by alex-konoval** [comment]
Thank you for answering. Would be great to add redirection or update a README.md to avoid confusion.

**Comment by shydie** [comment]
Updated https://github.com/shydie/scheduling-app/commit/f5b82ce3eea52e359abcf8536477facda6e53054
